name: count
version: v0.1.0
description: A plugin to count vulnerabilities in Trivy scan results
usage: trivy count [flags] [image]
platforms:
  - os: darwin
    arch: arm64
    bin: ./darwin_arm64/trivy-plugin-count
  - os: linux
    arch: amd64
    bin: ./linux_amd64/trivy-plugin-count
  - os: windows
    arch: amd64
    bin: ./windows_amd64/trivy-plugin-count.exe
