name: count
version: v0.1.0
description: A plugin to count vulnerabilities in Trivy scan results
usage: trivy count [flags] [image]
platforms:
  - os: darwin
    arch: arm64
    uri: https://github.com/TheTricky65/trivy-plugin-count/releases/download/all/plugin-count.0.1.0.tar.gz
  - os: linux
    arch: amd64
    uri: https://github.com/TheTricky65/trivy-plugin-count/releases/download/all/plugin-count.0.1.0.tar.gz
  - os: windows
    arch: amd64
    uri: https://github.com/TheTricky65/trivy-plugin-count/releases/download/all/plugin-count.0.1.0.tar.gz
