name: "severitycount"
version: "0.1.0"
repository: "https://github.com/example/trivy-plugin-hello"
maintainer: "You"
summary: "Hello plugin"
description: |
  A basic test plugin that prints Hello World from a Python script.
output: false

platforms:
  - selector:
      os: darwin
      arch: arm64
    uri: ./trivy-sev
    bin: ./trivy-sev
