name: "hello"
version: "0.1.0"
repository: "https://github.com/TheTricky65/trivy-plugin-severitycount"
maintainer: "TheTricky65"
summary: "Count plugin + severity counting"
description: |
  Counts vulnerabilities by severity from a Trivy JSON report.
output: false

platforms:
  - selector:
      os: darwin
      arch: arm64
    uri: ./hello.sh
    bin: ./hello.sh
